// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"api/api"
	"api/app"
	"api/config"
	"api/db"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp() (*app.App, error) {
	configConfig := config.NewConfig()
	dbDB, err := db.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	service := db.NewService(dbDB)
	helloAPI := api.NewHelloAPI(configConfig, service)
	engine, err := app.NewEngine(configConfig, helloAPI)
	if err != nil {
		return nil, err
	}
	appApp := app.NewApp(engine, configConfig)
	return appApp, nil
}

// wire.go:

var appSet = wire.NewSet(app.NewEngine, config.NewConfig, db.NewDB, db.NewService, api.NewHelloAPI)
