// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api_src

import (
	"api/api_src/app"
	"api/api_src/config"
	"api/api_src/controller"
	"api/api_src/logger"
	"api/api_src/service"
	"api/api_src/store"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp() (*app.App, error) {
	configConfig := config.NewConfig()
	loggerLogger, err := logger.NewLogger()
	if err != nil {
		return nil, err
	}
	dbClient, err := store.NewDBClient(configConfig)
	if err != nil {
		return nil, err
	}
	accountService := service.NewAccountService(configConfig, dbClient, loggerLogger)
	accountAPI := controller.NewAccountAPI(configConfig, loggerLogger, accountService)
	stationService := service.NewStationService(configConfig, dbClient, loggerLogger)
	stationAPI := controller.NewStationAPI(configConfig, loggerLogger, stationService)
	recordService := service.NewRecordService(configConfig, dbClient, loggerLogger)
	recordAPI := controller.NewRecordAPI(configConfig, loggerLogger, recordService)
	dataAPI := controller.NewDataAPI()
	engine, err := app.NewEngine(configConfig, loggerLogger, accountAPI, stationAPI, recordAPI, dataAPI)
	if err != nil {
		return nil, err
	}
	appApp := app.NewApp(engine, configConfig, loggerLogger)
	return appApp, nil
}

// wire.go:

var appSet = wire.NewSet(app.NewEngine, config.NewConfig, logger.NewLogger, store.NewDBClient, service.NewAccountService, service.NewStationService, service.NewRecordService, controller.NewDataAPI, controller.NewAccountAPI, controller.NewStationAPI, controller.NewRecordAPI)
