basePath: /
definitions:
  args.AccountRegisterArgs:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: 天津商业大学环境监测系统API文档
  termsOfService: https://www.tjcu.edu.cn/
  title: 天津商业大学环境监测系统API
  version: "1.0"
paths:
  /register:
    post:
      consumes:
      - application/json
      description: Register a new account with username and password
      parameters:
      - description: username and password
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/args.AccountRegisterArgs'
      produces:
      - application/json
      responses:
        "200":
          description: Account created, return account information
        "400":
          description: Username or password is missing
      summary: Register a new account
      tags:
      - accounts
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
