basePath: /
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: www.tjcu.edu.cn
info:
  contact: {}
  description: 天津商业大学环境监测系统API文档
  termsOfService: https://www.tjcu.edu.cn/
  title: 天津商业大学环境监测系统API
  version: "1.0"
paths: {}
swagger: "2.0"
