basePath: /api
definitions:
  args.AccountLoginArgs:
    properties:
      password:
        example: "123456"
        type: string
      username:
        example: bob
        type: string
    type: object
  args.AccountRegisterArgs:
    properties:
      password:
        example: "123456"
        type: string
      username:
        example: bob
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: 天津商业大学环境监测系统API文档
  termsOfService: https://www.tjcu.edu.cn/
  title: 天津商业大学环境监测系统API
  version: "1.0"
paths:
  /account:
    get:
      consumes:
      - application/json
      description: Get account information with token
      produces:
      - application/json
      responses:
        "200":
          description: Return account information
        "401":
          description: Token is incorrect
      security:
      - ApiKeyAuth: []
      summary: Get account information
      tags:
      - accounts
  /account/changePassword:
    post:
      consumes:
      - application/json
      description: Change account password
      produces:
      - application/json
      responses:
        "200":
          description: Return account information
        "401":
          description: Token is incorrect
      security:
      - ApiKeyAuth: []
      summary: Change Passsword
      tags:
      - accounts
  /account/regenrateToken:
    post:
      consumes:
      - application/json
      description: Regenrate account access token
      produces:
      - application/json
      responses:
        "200":
          description: Return account information with new token
        "401":
          description: Token is incorrect
      security:
      - ApiKeyAuth: []
      summary: Regenrate Access Token
      tags:
      - accounts
  /api:
    get:
      consumes:
      - application/json
      description: Get data
      produces:
      - application/json
      responses:
        "200":
          description: Return data
        "401":
          description: Token is incorrect
      security:
      - ApiKeyAuth: []
      summary: Get data
      tags:
      - api
  /login:
    post:
      consumes:
      - application/json
      description: Login to an account with username and password
      parameters:
      - description: username and password
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/args.AccountLoginArgs'
      produces:
      - application/json
      responses:
        "200":
          description: Login success, return account information
        "400":
          description: Username or password is missing
        "401":
          description: Username or password is incorrect
      summary: Login to an account
      tags:
      - accounts
  /records:
    get:
      consumes:
      - application/json
      description: query records data with time range, pagination & filters
      produces:
      - application/json
      responses:
        "200":
          description: return records json
      summary: get records by query
      tags:
      - records
  /records/template:
    get:
      consumes:
      - application/json
      description: generate record upload csv template
      produces:
      - application/json
      responses:
        "200":
          description: export csv template
      summary: download csv records
      tags:
      - records
  /records/upload:
    post:
      consumes:
      - application/json
      description: csv column - "sensorId"
      produces:
      - application/json
      responses:
        "200":
          description: return uploaded csv
      summary: upload csv records
      tags:
      - records
  /register:
    post:
      consumes:
      - application/json
      description: Register a new account with username and password
      parameters:
      - description: username and password
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/args.AccountRegisterArgs'
      produces:
      - application/json
      responses:
        "200":
          description: Account created, return account information
        "400":
          description: Username or password is missing
      summary: Register a new account
      tags:
      - accounts
  /sensors:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: return sensors by station_id
      summary: get sensors
      tags:
      - sensors
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: return sensor
      summary: create sensor
      tags:
      - sensors
  /stations:
    get:
      consumes:
      - application/json
      description: Get stations with params
      produces:
      - application/json
      responses:
        "200":
          description: Return station json array
      summary: Get stations
      tags:
      - stations
    post:
      consumes:
      - application/json
      description: Upsert stations
      produces:
      - application/json
      responses:
        "200":
          description: Return station json array
      summary: Upsert stations
      tags:
      - stations
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
