name: deploy to lambda
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.18.0"
      - name: Build binary
        run: |
          go install github.com/google/wire/cmd/wire@latest
          make wire
          make
