name: deploy to lambda
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.18.0"
      - name: Build binary
        run: |
          make deps
          make linux
      - name: Deploy to Server
        uses: mai-space/action-sshpass-rsync@v1
        with:
          host: wkstation.yiwei.dev
          user: root
          port: 22
          pass: ${{ secrets.DEPLOY_PASS }}
          local: api.exe
          remote: /root/api/api.exe
          runAfterDeployment: |
            cd ../somewhere/back/to
