name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: "Build And Publish"
        run: |
          docker build . --tag ghcr.io/tuc-environment/EnvMonitoringDashboard:latest
          docker push ghcr.io/tuc-environment/EnvMonitoringDashboard:latest
